services:

    dream_commerce_shop_appstore.object_manager:
        class: DreamCommerce\ShopAppstoreBundle\Doctrine\ObjectManager
        arguments:
            - @dream_commerce_shop_appstore.entity_manager
            - %dream_commerce_shop_appstore.objects%

    dream_commerce_shop_appstore.entity_manager:
        factory: ["@doctrine", getManager]
        class: Doctrine\ORM\EntityManager
        #arguments: ["default"] # injected by compiler pass
        public: false