parameters:
    dream_commerce_shop_appstore.model_manager_name: null

services:
    dream_commerce_shop_appstore.shop_manager:
          class: DreamCommerce\ShopAppstoreBundle\Entity\ShopManager
          arguments: ["@dream_commerce_shop_appstore.entity_manager",DreamCommerce\ShopAppstoreBundle\Entity\Shop]

    dream_commerce_shop_appstore.entity_manager:
          factory_service:  doctrine
          factory_method:   getManager
          class: Doctrine\ORM\EntityManager
          arguments: [%dream_commerce_shop_appstore.model_manager_name%]
          #public: false