dream_commerce_shop_appstore_responder:
    path:     "/responder"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Responder:index }
    methods: [POST]

dream_commerce_shop_appstore.unpaid:
    path:     "/exception/unpaid"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Exception:unpaid }

dream_commerce_shop_appstore.unsubscribed:
    path:     "/exception/unsubscribed"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Exception:unsubscribed }

dream_commerce_shop_appstore.not_installed:
    path:     "/exception/not_installed"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Exception:notInstalled }

dream_commerce_shop_appstore.reinstall:
    path:     "/exception/reinstall"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Exception:reinstall }

dream_commerce_shop_appstore.upgrade:
    path:     "/exception/upgrade"
    defaults: { _controller: DreamCommerceShopAppstoreBundle:Exception:upgrade }
