parameters:
    dream_commerce_shop_appstore.logger: logger

services:
#    dream_commerce_shop_appstore.client:
#        class: DreamCommerce\ShopAppstoreBundle\Client
#        arguments: [@logger, %dream_commerce_shop_appstore.applications%, @request_stack]
#        private: true

    #dream_commerce_shop_appstore.token_refresher:
#        class: DreamCommerce\ShopAppstoreBundle\Utils\TokenRefresher
#        arguments: [@dream_commerce_shop_appstore.token_manager]

    dream_commerce_shop_appstore.request_validator:
        class: DreamCommerce\ShopAppstoreBundle\Utils\RequestValidatorService
        calls:
            - [setRequestStack, [@request_stack]]

#    dream_commerce_shop_appstore.controller_filter:
#        class: DreamCommerce\ShopAppstoreBundle\EventListener\ApplicationControllerListener
#        arguments:
#            - %dream_commerce_shop_appstore.applications%
#            - %dream_commerce_shop_appstore.routes%
#            - @dream_commerce_shop_appstore.shop_manager
#            - @dream_commerce_shop_appstore.token_refresher
#            - %minimal_version%
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    dream_commerce_shop_appstore.url:
        class: DreamCommerce\ShopAppstoreBundle\Utils\Url
        arguments: [@request_stack,@dream_commerce_shop_appstore.request_validator,@router]

    dream_commerce_shop_appstore.locale_listener:
        class: DreamCommerce\ShopAppstoreBundle\EventListener\LocaleListener
        arguments: [ %locale% ]
        tags:
            - { name: kernel.event_subscriber }

#    dream_commerce_shop_appstore.event.install:
#        class: DreamCommerce\ShopAppstoreBundle\EventListener\AppstoreListener
#        arguments: [@dream_commerce_shop_appstore.shop_manager, @dream_commerce_shop_appstore.token_manager, @dream_commerce_shop_appstore.billing_manager, @dream_commerce_shop_appstore.subscription_manager]
#        tags:
#            # todo: event names constants (probably have to convert to xml)
#            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.install, method: onInstall }
#            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.uninstall, method: onUninstall }
#            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.billing_install, method: onPaid }
#            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.subscription_paid, method: onSubscribed }
#            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.upgrade, method: onUpgraded }

    dream_commerce_shop_appstore.twig_tags:
        class: DreamCommerce\ShopAppstoreBundle\Twig\PathExtension
        arguments: [@dream_commerce_shop_appstore.url]
        public: false
        tags:
            - { name: twig.extension }


    #dream_commerce_shop_appstore.shop_manager:
#        arguments: [@dream_commerce_shop_appstore.shop_manager]